name: poc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
