// Mocks generated by Mockito 5.3.2 from annotations
// in poc/test/presentation/login/bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poc/core/errors/failures.dart' as _i6;
import 'package:poc/domain/entities/user_entity.dart' as _i7;
import 'package:poc/domain/repositories/login_repository.dart' as _i2;
import 'package:poc/domain/usecases/get_token_user_login_use_cases.dart' as _i8;
import 'package:poc/domain/usecases/google_login_use_case.dart' as _i9;
import 'package:poc/domain/usecases/user_login_use_cases.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeILoginRepository_0 extends _i1.SmartFake
    implements _i2.ILoginRepository {
  _FakeILoginRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserLoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLoginUseCase extends _i1.Mock implements _i4.UserLoginUseCase {
  MockUserLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILoginRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeILoginRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ILoginRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
            _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [GetTokenUserLoginUseCaseImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTokenUserLoginUseCaseImp extends _i1.Mock
    implements _i8.GetTokenUserLoginUseCaseImp {
  MockGetTokenUserLoginUseCaseImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILoginRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeILoginRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ILoginRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [GoogleLoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleLoginUseCase extends _i1.Mock
    implements _i9.GoogleLoginUseCase {
  MockGoogleLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILoginRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeILoginRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ILoginRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
