// Mocks generated by Mockito 5.3.2 from annotations
// in poc/test/data/data_sources/get_user_by_google_login_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poc/data/external/google_sign_in.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleSignInExternal].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInExternal extends _i1.Mock
    implements _i2.GoogleSignInExternal {
  MockGoogleSignInExternal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> googleSignInExternal() => (super.noSuchMethod(
        Invocation.method(
          #googleSignInExternal,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> googleLogout() => (super.noSuchMethod(
        Invocation.method(
          #googleLogout,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
